config/routes.rb
Vishfacts::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users
  resources :facts

  get '/submit' => 'facts#new', as: :submit
  get '/all' => 'facts#all', as: :all

  root :to => 'facts#index'
end

app/models/fact.rb
class Fact < ActiveRecord::Base
  attr_accessible :body, :disabled

  def self.random
    if (c = count) > 0
      first(offset: rand(c))
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  if Rails.env.production?
    devise :database_authenticatable,
           :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  # GET /facts
  # GET /facts.json
  def index
    @fact = Fact.random
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @facts }
    end
  end

  def all
    @facts = Fact.all
  end

  # GET /facts/1
  # GET /facts/1.json
  def show
    @fact = Fact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fact }
    end
  end

  # GET /facts/new
  # GET /facts/new.json
  def new
    @fact = Fact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fact }
    end
  end

  # GET /facts/1/edit
  def edit
    @fact = Fact.find(params[:id])
  end

  # POST /facts
  # POST /facts.json
  def create
    @fact = Fact.new(params[:fact])

    respond_to do |format|
      if @fact.save
        format.html { redirect_to @fact, notice: 'Fact was successfully created.' }
        format.json { render json: @fact, status: :created, location: @fact }
      else
        format.html { render action: "new" }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /facts/1
  # PUT /facts/1.json
  def update
    @fact = Fact.find(params[:id])

    respond_to do |format|
      if @fact.update_attributes(params[:fact])
        format.html { redirect_to @fact, notice: 'Fact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facts/1
  # DELETE /facts/1.json
  def destroy
    @fact = Fact.find(params[:id])
    @fact.destroy

    respond_to do |format|
      format.html { redirect_to facts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/facts/_form.html.erb
<%= form_for(@fact) do |f| %>
  <div class="field">
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facts/all.html.erb
<img src='/assets/superman-vish.png' alt='Vish is superman.' />

<% @facts.each do |fact| %>
  <h2><%= fact.body %></h2>
<% end %>

app/views/facts/edit.html.erb
<h1>Editing fact</h1>

<%= render 'form' %>

<%= link_to 'Show', @fact %> |
<%= link_to 'Back', facts_path %>

app/views/facts/index.html.erb
<img src='/assets/superman-vish.png' alt='Vish is superman.' />

<h2><%= @fact.body %></h2>

app/views/facts/new.html.erb
<p>All facts must start with the word 'Vish', 'Vishvananda', or 'Vishy'.</p>

<p class='example'>Example: "Vish applies a binary function with one argument, it curries itself out of fear."</p>

<%= render 'form' %>

app/views/facts/show.html.erb
<img src='/assets/superman-vish.png' alt='Vish is superman.' />

<h2><%= @fact.body %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vishfacts</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id='wrapper'>
      <%= yield %>
    </div>

    <footer>
      <nav>
        <li><a href='<%= root_url %>'>Random</a></li>
        <li><a href='<%= all_url %>'>View all</a></li>
        <li><a href='<%= submit_url %>'>Submit!</a></li>
      </nav>
    </footer>


    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-34635204-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </body>
</html>